Add Conecta components
conekta/conekta-magento pull request #62
Opened 2018-07-12 18:31 UTC by cone-7

Added new implementation of conecta components to magento.

2018-07-12 20:01 UTC, danielconekta commented on app/design/frontend/base/default/layout/card.xml
> +            <action method="setText"><text><![CDATA[<script src="https://cdn.conekta.io/iframe/latest/conekta-iframe.js"></script>]]></text></action>
creo que hay que agregarle un query param a la url por si en algun momento el codigo se cambia, que no quedé en cache el js, por ejemplo conekta-iframe.js?v=123 o algo así

2018-07-12 21:13 UTC, danielconekta commented on app/design/frontend/base/default/layout/card.xml
> +            <action method="setText"><text><![CDATA[<script src="https://cdn.conekta.io/iframe/latest/conekta-iframe.js"></script>]]></text></action>
lo mismo sería para cualquier link que haga referencia al cdn

2018-07-12 21:14 UTC, danielconekta approved these changes

2018-07-12 21:19 UTC, fruizg0302 approved these changes

2018-07-12 21:34 UTC, edenriquez requested changes
Solo quedo a la espera de que se compare por tipo de error y le doy mi like :)

2018-07-12 22:49 UTC, cone-7 commented on app/design/frontend/base/default/layout/card.xml
> +            <action method="setText"><text><![CDATA[<script src="https://cdn.conekta.io/iframe/latest/conekta-iframe.js"></script>]]></text></action>
@danielconekta por ahora se quedará de esta forma por que no es tan sencillo cambiar la url en cada version de libreria.

2018-07-13 19:41 UTC, eduenriquez commented on app/design/frontend/base/default/template/card/token.phtml
> +          alert('Error en el nombre del titular');
aqui se te paso dejar el `alert(_getError()`)

2018-07-13 19:48 UTC, edenriquez approved these changes

2023-05-01 13:02 UTC, closed without merging